name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: gabrielrufino/check-ci@main
      - uses: actions/checkout@v4
      - uses: gabrielrufino/node-pkg-cd@v1
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
