name: Profiling

on:
  - push
  - pull_request

jobs:
  profiling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run profiling
      - uses: actions/upload-artifact@v3
        with:
          name: Profiling
          path: '.clinic'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
